FROM golang:alpine AS builder
WORKDIR /app

COPY . .
WORKDIR /app/microservices/order
RUN go mod tidy
RUN go build -o order_app cmd/main.go

FROM alpine:latest
WORKDIR /root/

# Variáveis de ambiente
ENV DB_DRIVER=mysql
ENV APPLICATION_PORT=3000
ENV ENV=development

COPY --from=builder /app/microservices/order/order_app .
CMD ["./order_app"]