FROM golang:alpine AS builder
WORKDIR /app

COPY . .
WORKDIR /app/microservices/shipping
RUN go mod tidy
RUN go build -o shipping_app cmd/main.go

FROM alpine:latest
WORKDIR /root/

# Variáveis de ambiente
# ENV DB_DRIVER=mysql
ENV APPLICATION_PORT=3003
ENV ENV=development

COPY --from=builder /app/microservices/shipping/shipping_app .
CMD ["./shipping_app"]